From 928ea9b0776d616b723a1f35f85728e8c91a6082 Mon Sep 17 00:00:00 2001
From: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
Date: Sun, 24 Oct 2021 15:18:05 +1300
Subject: [PATCH 257/361] CVE-2020-25722 pytest: assertRaisesLdbError invents a
 message if you're lazy

This makes it easier to convert tests that don't have good messages.

BUG: https://bugzilla.samba.org/show_bug.cgi?id=14564

Signed-off-by: Douglas Bagnall <douglas.bagnall@catalyst.net.nz>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>
---
 python/samba/tests/__init__.py | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/python/samba/tests/__init__.py b/python/samba/tests/__init__.py
index 388036939cd..e04ddcb4ba8 100644
--- a/python/samba/tests/__init__.py
+++ b/python/samba/tests/__init__.py
@@ -317,6 +317,8 @@ class TestCase(unittest.TestCase):
 
     def assertRaisesLdbError(self, errcode, message, f, *args, **kwargs):
         """Assert a function raises a particular LdbError."""
+        if message is None:
+            message = f"{f.__name__}(*{args}, **{kwargs})"
         try:
             f(*args, **kwargs)
         except ldb.LdbError as e:
-- 
2.30.2

